### ISSUE TITLE
[Crash-Report] Could not execute entrypoint stage 'main' due to errors, provided by 'moreweaponry'

### ISSUE THREAD

**Issue by lospejos** [DakotaPride/More-Weaponry-1.18#11]
**Describe the bug**
On starting the world using `qfapi-4.0.0-beta.16_qsl-3.0.0-beta.18_fapi-0.64.0_mc-1.19.2` (updated recently) with mod `moreweaponry-v2.3+1.19.2` I have a crash:
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'moreweaponry'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:63)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:61)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:46)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.NoSuchMethodError: 'void net.kyrptonaught.customportalapi.api.CustomPortalBuilder.registerPortal()'
	at net.DakotaPride.moreweaponry.common.world.dimension.MoreWeaponryPortals.registerMoreWeaponryPortals(MoreWeaponryPortals.java:13)
	at net.DakotaPride.moreweaponry.common.MoreWeaponry.onInitialize(MoreWeaponry.java:2550)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:52)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59)
	... 18 more
```

**To Reproduce**
1. Install QFAPI `qfapi-4.0.0-beta.16_qsl-3.0.0-beta.18_fapi-0.64.0_mc-1.19.2` (updated recently) with mod `moreweaponry-v2.3+1.19.2`
2. Start the world
3. See crash

**Expected behavior**
World starts normally

**Screenshots**
No screenshots

**Desktop (please complete the following information):**
 - Java Version: Java 18

**Additional context**
[crash-2022-10-21_19.57.32-client.txt](https://github.com/DakotaPride/More-Weaponry/files/9841005/crash-2022-10-21_19.57.32-client.txt)

Also I think that Quilted Fabric API authors made breaking changes in Fabric API, and this is the cause of this crash, because on previous `qfapi-4.0.0-beta.14_qsl-3.0.0-beta.18_fapi-0.62.0_mc-1.19.2`  it worked ok.

Although It may seems that is the QFAPI bug rather than your mod's bug I will appreciate if you do refactor your mod to be compatible with QFAPI. Thanks!

**Comment by DakotaPride** [comment]
I think I know what the issue is and it will hopefully be 'fixed' in the next update. The most recent version of Quilted Fabric API syncs with a Fabric API version higher than 0.60.0, which is what More Weaponry uses as a base API (While More Weaponry should be able to work with other 1.19.2 Fabric APIs, I cannot say the same about Quilted Fabric APIs, as I am not experienced with the api/loader). As for refactoring More Weaponry to be compatible with Quilted Fabric API, again, I'm not sure where I would even start in order to do this, I'm sorry. Thank you for your patience and understanding!

(sidenote: the release will most likely be on Monday, as curseforge doesn't typically accept mod uploads on weekends. Though, I will work to make sure the release is good until then)

**Comment by DakotaPride** [comment]
@lospejos While Curseforge has not yet accepted the update, I have updated it on [Modrinth](https://modrinth.com/mod/more-weaponry/version/v2.3.1) if you would like download it from there

(Though, here's the [curseforge](https://www.curseforge.com/minecraft/mc-mods/more-weaponry/files/4049760) link for when it does become avaliable)
